### ISSUE TITLE
Error while loading shared libraries: libboost_filesystem

### ISSUE THREAD

**Issue by TobiasSekan** [golddranks/ganbare#1]
> $ sudo ./build_musl.sh

> tsc: error while loading shared libraries: libboost_filesystem.so.1.62.0: cannot open shared object file: No such file or directory
> TypeScript built.
> main.scss:1 Error: InvalidInstruction
> main.scss:2 Error: InvalidInstruction
> main.scss:3 Error: InvalidInstruction
> main.scss:4 Error: InvalidInstruction
> main.scss:5 Error: InvalidInstruction
> main.scss:6 Error: InvalidInstruction
> main.scss:8 Error: InvalidInstruction
> main.scss:9 Error: InvalidInstruction
> main.scss:10 Error: InvalidInstruction
> main.scss:11 Error: InvalidInstruction
> main.scss:12 Error: InvalidInstruction
> main.scss:14 Error: InvalidInstruction
> main.scss:15 Error: InvalidInstruction
> main.scss:16 Error: InvalidInstruction
> main.scss:17 Error: InvalidInstruction
> main.scss:18 Error: InvalidInstruction
> main.scss:19 Error: InvalidInstruction
> main.scss:20 Error: InvalidInstruction
> main.scss:21 Error: InvalidInstruction
> main.scss:23 Error: InvalidInstruction
> main.scss:24 Error: InvalidInstruction
> main.scss:25 Error: InvalidInstruction
> main.scss:26 Error: InvalidInstruction
> main.scss:28 Error: InvalidInstruction
> main.scss:29 Error: InvalidInstruction
> main.scss:30 Error: InvalidInstruction
> main.scss:32 Error: InvalidInstruction
> main.scss:33 Error: InvalidInstruction
> main.scss:34 Error: InvalidInstruction
> main.scss:35 Error: InvalidInstruction
> main.scss:36 Error: InvalidInstruction
> main.scss:37 Error: InvalidInstruction
> main.scss:39 Error: InvalidInstruction
> main.scss:41 Error: InvalidInstruction
> main.scss:42 Error: InvalidInstruction
> main.scss:43 Error: InvalidInstruction
> main.scss:44 Error: InvalidInstruction
> main.scss:45 Error: InvalidInstruction
> main.scss:46 Error: InvalidInstruction
> main.scss:47 Error: InvalidInstruction
> main.scss:48 Error: InvalidInstruction
> main.scss:49 Error: InvalidInstruction
> main.scss:50 Error: InvalidInstruction
> main.scss:51 Error: InvalidInstruction
> main.scss:53 Error: InvalidInstruction
> main.scss:55 Error: InvalidInstruction
> main.scss:56 Error: InvalidInstruction
> main.scss:58 Error: InvalidInstruction
> main.scss:60 Error: InvalidInstruction
> main.scss:61 Error: InvalidInstruction
> main.scss:62 Error: InvalidInstruction
> main.scss:63 Error: InvalidInstruction
> main.scss:64 Error: InvalidInstruction
> main.scss:65 Error: InvalidInstruction
> main.scss:67 Error: InvalidInstruction
> main.scss:69 Error: InvalidInstruction
> main.scss:70 Error: InvalidInstruction
> main.scss:71 Error: InvalidInstruction
> Assembly done: 14 ms
> SCSS built.
> Unable to find image 'golddranks/ganbare_build:latest' locally
> latest: Pulling from golddranks/ganbare_build
> 386a066cd84a: Pull complete 
> 49b0ff922ae1: Pull complete 
> 04ea8ca892c9: Pull complete 
> 2c80fed4a545: Pull complete 
> d95182737ac3: Pull complete 
> 995b0384770a: Pull complete 
> 7554ad1d54dd: Pull complete 
> d8fac1abce9f: Pull complete 
> Digest: sha256:c5600a977e4442d4b32adef32aa9907f83e7f85bcbc1d089625bd5192fd43abe
> Status: Downloaded newer image for golddranks/ganbare_build:latest
> [ ok ] Starting PostgreSQL 9.4 database server: main.
> Dropping database: ganbare_build
> Creating database: ganbare_build
> Running migration 20160821164924
> Running migration 20161022173507
> Running migration 20161108232358
> Running migration 20161211000310
> Running migration 20161217140710
> Running migration 20170110162205
> Running migration 20170115174212
> Running migration 20170116164402
> Running migration 20170123230428
> Running migration 20170127045311
>     Updating registry `https://github.com/rust-lang/crates.io-index`
>     Updating git repository `https://github.com/golddranks/pencil`
>  Downloading time v0.1.36
>  Downloading multi_mut v0.1.3
>  Downloading hyper v0.9.18
>  Downloading url v1.4.0
>  Downloading libc v0.2.20
>  Downloading pkg-config v0.3.9
>  Downloading gcc v0.3.42
>  Downloading mime_multipart v0.3.5
>  Downloading traitobject v0.1.0
>  Downloading phf v0.7.21
>  Downloading phf_shared v0.7.21
>  Downloading siphasher v0.2.1
>  Downloading phf_codegen v0.7.21
>  Downloading phf_generator v0.7.21
>  Downloading clap v2.20.1
>  Downloading hyper v0.10.3
>  Downloading rpassword v0.3.1
>  Downloading strsim v0.6.0
>  Downloading term_size v0.2.2
>  Downloading unicode-segmentation v1.0.1
>  Downloading syn v0.10.8
>  Downloading quote v0.3.12
>  Downloading unicode-xid v0.0.4
>    Compiling gcc v0.3.42
>    Compiling data-encoding v1.1.2
>    Compiling regex-syntax v0.3.9
>    Compiling language-tags v0.2.2
>    Compiling matches v0.1.4
>    Compiling bitflags v0.7.0
>    Compiling encoding_index_tests v0.1.4
>    Compiling encoding-index-japanese v1.20141219.5
>    Compiling backtrace v0.2.3
>    Compiling lazy_static v0.2.2
>    Compiling winapi-build v0.1.1
>    Compiling quote v0.3.12
>    Compiling byteorder v0.3.13
>    Compiling num-traits v0.1.36
>    Compiling multi_mut v0.1.3
>    Compiling dbghelp-sys v0.2.0
>    Compiling unicode-xid v0.0.4
>    Compiling typeable v0.1.2
>    Compiling traitobject v0.0.1
>    Compiling encoding-index-simpchinese v1.20141219.5
>    Compiling winapi v0.2.8
>    Compiling buf-read-ext v0.2.0
>    Compiling traitobject v0.1.0
>    Compiling unsafe-any v0.4.1
>    Compiling rustc-demangle v0.1.3
>    Compiling typemap v0.3.3
>    Compiling rustc-serialize v0.3.22
>    Compiling openssl-sys-extras v0.7.14
>    Compiling ansi_term v0.9.0
>    Compiling siphasher v0.2.1
>    Compiling cfg-if v0.1.0
>    Compiling libc v0.2.20
>    Compiling rand v0.3.15
>    Compiling time v0.1.36
>    Compiling pq-sys v0.2.7
>    Compiling itertools v0.4.19
>    Compiling semver v0.1.20
>    Compiling num_cpus v1.2.1
>    Compiling vec_map v0.6.0
>    Compiling kernel32-sys v0.2.2
>    Compiling rust-crypto v0.2.36
>    Compiling pkg-config v0.3.9
>    Compiling openssl-sys v0.7.17
>    Compiling bufstream v0.1.2
>    Compiling encoding-index-korean v1.20141219.5
>    Compiling num-integer v0.1.32
>    Compiling uuid v0.3.1
>    Compiling try_map v0.2.0
>    Compiling unicode-bidi v0.2.4
>    Compiling memchr v0.1.11
>    Compiling aho-corasick v0.5.3
>    Compiling log v0.3.6
>    Compiling encoding-index-tradchinese v1.20141219.5
>    Compiling hpack v0.2.0
>    Compiling mime v0.2.2
>    Compiling lazy_static v0.1.16
>    Compiling num-iter v0.1.32
>    Compiling num v0.1.36
>    Compiling solicit v0.4.4
>    Compiling unicode-segmentation v1.0.1
>    Compiling syn v0.10.8
>    Compiling term_size v0.2.2
>    Compiling openssl v0.7.14
>    Compiling utf8-ranges v0.1.3
>    Compiling openssl v0.8.3
>    Compiling tempdir v0.3.5
>    Compiling httparse v1.2.1
>    Compiling quick-error v1.1.0
>    Compiling thread-id v2.0.0
>    Compiling thread_local v0.2.7
>    Compiling regex v0.1.80
>    Compiling env_logger v0.3.5
>    Compiling chrono v0.2.25
>    Compiling diesel v0.9.1
>    Compiling dotenv v0.8.0
>    Compiling handlebars v0.16.1
>    Compiling textnonce v0.4.1
>    Compiling termios v0.2.2
>    Compiling rpassword v0.3.1
>    Compiling strsim v0.6.0
>    Compiling rustc_version v0.1.7
>    Compiling unicode-normalization v0.1.3
>    Compiling idna v0.1.0
>    Compiling hyper v0.10.3
>    Compiling unicase v1.4.0
>    Compiling phf_shared v0.7.21
>    Compiling url v1.4.0
>    Compiling phf v0.7.21
>    Compiling binary_macros v0.2.0
>    Compiling encoding-index-singlebyte v1.20141219.5
>    Compiling encoding v0.2.33
>    Compiling email v0.0.13
>    Compiling lettre v0.6.1
>    Compiling backtrace-sys v0.1.5
>    Compiling unicode-width v0.1.4
>    Compiling clap v2.20.1
>    Compiling dotenv_codegen v0.10.0
>    Compiling dotenv_macros v0.10.0
>    Compiling cookie v0.2.5
>    Compiling openssl-verify v0.1.0
>    Compiling hyper v0.9.18
>    Compiling phf_generator v0.7.21
>    Compiling phf_codegen v0.7.21
>    Compiling mime_guess v1.8.1
>    Compiling mime_multipart v0.3.5
>    Compiling formdata v0.10.2
>    Compiling pencil v0.3.0 (https://github.com/golddranks/pencil?branch=modifications_for_ganbare#d4639507)
>    Compiling diesel_codegen_shared v0.9.0
>    Compiling diesel_codegen v0.9.0
>    Compiling error-chain v0.5.0 (https://github.com/golddranks/error-chain.git?branch=tweaks_for_ganbare#76d5ccfa)
>    Compiling ganbare_backend v0.1.0 (file:///workdir/ganbare_backend)
> error: environment variable `GANBARE_BUILDTIME_PEPPER` not defined
>   --> ganbare_backend/src/password.rs:51:32
>    |
> 51 |     let build_pepper = base64!(dotenv!("GANBARE_BUILDTIME_PEPPER"));
>    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> error: expected string literal
>   --> ganbare_backend/src/password.rs:51:32
>    |
> 51 |     let build_pepper = base64!(dotenv!("GANBARE_BUILDTIME_PEPPER"));
>    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> error: aborting due to 2 previous errors
> 
> error: Could not compile `ganbare_backend`.
> 
> To learn more, run the command again with --verbose.

**Comment by TobiasSekan** [comment]
content of my `.env` file

> GANBARE_DATABASE_URL=postgres://drasa@localhost/ganbare_dev
> GANBARE_RUNTIME_PEPPER=1234567890123456789012345678901234
> GANBARE_EMAIL_SERVER=mail.yourisp.net:25
> GANBARE_SITE_DOMAIN=true

**Comment by golddranks** [comment]
Oops, sorry, I missed this. It seems that you don't have a working TypeScript compiler, which is used to build the frontend. Try to run `tsc`, does it blow up too?

**Comment by TobiasSekan** [comment]
Sorry that was my fault, under Arch-Linux SASS is not SASS

SASS is a Z80 Assembler (see https://aur.archlinux.org/packages/sass/)

The correct package is Ruby-SASS (https://aur.archlinux.org/packages/ruby-sass/)
