### ISSUE TITLE
Dockerfiles are gone

### ISSUE THREAD

**Issue by TomasTomecek** [golddranks/ganbare#2]
I got here based on [this reddit thread](https://www.reddit.com/r/rust/comments/5ds9fb/help_with_static_linking/), because I have the same problem. Unfortunately the referenced dockerfiles are now gone.

**Comment by golddranks** [comment]
Oops, sorry, I missed this issue completely! The dockerfile referenced in Reddit has changed path and are now in the scripts subdirectory!

**Comment by TomasTomecek** [comment]
Thank you! Got it.
